routes/index.py
import os
import uuid

<<<<<<< HEAD
=======
import redis
>>>>>>> error fixed and gif added
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
<<<<<<< HEAD
    current_app)
=======
    current_app, flash)
>>>>>>> error fixed and gif added
from werkzeug.datastructures import FileStorage

import config
from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user, cache
<<<<<<< HEAD
=======
from task_queue import send_mail_async
>>>>>>> error fixed and gif added
from utils import log

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)




@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
<<<<<<< HEAD
=======
        flash("用户名或密码错误")
>>>>>>> error fixed and gif added
        return redirect(url_for('.index'))
    else:
        session_id = str(uuid.uuid4())
        key = 'session_id_{}'.format(session_id)
        log('index login <{}>  <{}>'.format(key,u.id))
        cache.set(key, u.id)

        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        return response

@main.route("/userlogin")
def user_login():
    u = current_user()
    return render_template("userlogin.html", user=u)



@main.route("/setting")
def setting():
    u = current_user()
    board_id = int(request.args.get('board_id', -1))
    return render_template("setting.html",u=u,bid=board_id)

@main.route("/setting/password", methods=['POST'])
def change_password():
    form = request.form.to_dict()
    # 用类函数来判断
    user = current_user()
    u = User.confirm_password(form,user)
    return redirect(url_for('.setting'))


@main.route("/setting/username", methods=['POST'])
def change_username():
    form = request.form.to_dict()
    # 用类函数来判断
    user = current_user()
    u = User.confirm_username(form)
    return redirect(url_for('.setting'))

<<<<<<< HEAD
tokens = {}

def create_token(form):
    username = form['username']
    uid = User.one(username=username)
    if uid is None:
        return None
    token = str(uuid.uuid4())
    tokens[token] = uid
=======
# tokens = {}
tokens = redis.StrictRedis()

def create_token(form):
    username = form['username']
    u = User.one(username=username)
    uid = int(u.id)
    if uid is None:
        return None
    token = str(uuid.uuid4())
    # tokens[token] = uid
    tokens.set(token, uid)
>>>>>>> error fixed and gif added
    return token

@main.route("/lostpassword")
def lost_password():
    u = current_user()
    return render_template("lostpassword.html", user=u)


@main.route("/reset/send", methods=['POST'])
def reset_send():
    form = request.form.to_dict()
    # 用类函数来判断
    token = create_token(form)
    title = '重置密码'
<<<<<<< HEAD
    content = 'http://148.70.34.62/reset/view?token={}'.format(token)
    send_mail(
=======
    content = 'http://148.70.34.62//reset/view?token={}'.format(token)
    send_mail_async(
>>>>>>> error fixed and gif added
        subject=title,
        author=config.admin_mail,
        to=config.test_mail,
        content=content,
    )
    return redirect(url_for('.index'))


@main.route("/reset/view")
def reset_view():
    token = request.args['token']
    # 用类函数来判断
    print('reset_views token',token, tokens)
<<<<<<< HEAD
    if token in tokens:
=======
    if tokens.exists(token):
>>>>>>> error fixed and gif added
        return render_template("reset_view.html",token=token)
    else:
        return redirect(url_for('.index'))


@main.route('/reset/update', methods=['POST'])
def reset_update():
    token = request.args['token']
<<<<<<< HEAD
    user_id = tokens.get(token, None)
    print('reset_update token', token, tokens)
    if user_id is None:
        return redirect(url_for('.index'))
    else:
        print('reset_update password',request.form['password'])
        password = User.salted_password(request.form['password'])
        User.update(id=user_id, password=password)
=======
    user_id = int(tokens.get(token))
    print('user_id,,', user_id)
    print('reset_update token', token, tokens)
    if tokens.exists(token):
        new_pass = request.form.get('password')
        print('reset_update password', new_pass)
        User.update(user_id, password=User.salted_password(new_pass))
        tokens.delete(token)
        return redirect('/')
    else:
>>>>>>> error fixed and gif added
        return redirect(url_for('.index'))


def created_topic(user_id):
    # O(n)
    ts = Topic.all(user_id=user_id)
    return ts
    #
    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # O(k)+O(m*n)
    rs = Reply.all(user_id=user_id)
    ts = []
    for r in rs:
        t = Topic.one(id=r.topic_id)
        ts.append(t)
    return ts
    #
    # k = 'replied_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     rs = Reply.all(user_id=user_id)
    #     ts = []
    #     for r in rs:
    #         t = Topic.one(id=r.topic_id)
    #         ts.append(t)
    #
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #
    #     return ts


@main.route('/profile')
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    # filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    filename = str(uuid.uuid4())
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.profile'))


@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:2000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)

routes/topic.py
import time

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    u = current_user()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, u=u)

@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/delete")
@csrf_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
<head>
<body>

<!-- navbar -->
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <ul class='nav pull-right'>
        <li><a href='./topic/topic.html'>首页</a></li>

        <li><a href='/setting'>个人信息设置</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/signup'>注册</a></li>
        <li><a href='/signin'>登录</a></li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>


{% block main %}
{% endblock %}

</body>

templates/index.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>bbs club</title>#}
{#    <link rel="stylesheet" href="/static/css/bootstrap.min.css">#}
{#</head>#}
{#<body>#}
{#    <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">#}
{#        <div class="control-group">#}
{#            <label class="control-label">用户名</label>#}
{#            <div class="controls">#}
{#                <input type="text" class="input-xlarge" name="username">#}
{#            </div>#}
{#        </div>#}
{#        <div class="control-group">#}
{#            <label class="control-label">密码</label>#}
{#            <div class="controls">#}
{#                <input type="text" class="input-xlarge" name="password">#}
{#            </div>#}
{#        </div>#}
{#        <div class="form-actions">#}
{#            <input type="submit" class="span-primary" value="注册">#}
{#        </div>#}
{#    </form>#}
{#    <form class="form-horizontal" method="post" action="{{ url_for('.login') }}">#}
{#        <div class="control-group">#}
{#            <label class="control-label">用户名</label>#}
{#            <div class="controls">#}
{#                <input type="text" class="input-xlarge" name="username">#}
{#            </div>#}
{#        </div>#}
{#        <div class="control-group">#}
{#            <label class="control-label">密码</label>#}
{#            <div class="controls">#}
{#                <input type="text" class="input-xlarge" name="password">#}
{#            </div>#}
{#        </div>#}
{#        <div class="form-actions">#}
{#            <input type="submit" class="span-primary" value="登录">#}
{#        </div>#}
{#    </form>#}
{#    <form class="form-horizontal" method="post" action="{{ url_for('.reset_send') }}">#}
{#        <div class="control-group">#}
{#            <label class="control-label">用户名</label>#}
{#            <div class="controls">#}
{#                <input type="text" class="input-xlarge" name="username">#}
{#            </div>#}
{#        </div>#}
{#        <div class="form-actions">#}
{#            <input type="submit" class="span-primary" value="找回密码">#}
{#        </div>#}
{#    </form>#}
{#</body>#}
{#</html>#}


<!DOCTYPE html>
<!-- saved from url=(0046)https://vcb-s.com/wp-login.php?action=register -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN"><!--<![endif]--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>注册表单</title>
<link rel="dns-prefetch" href="https://s.w.org/">
<link rel="stylesheet" id="dashicons-css" href="/static/css/dashicons.min.css" type="text/css" media="all">
<link rel="stylesheet" id="buttons-css" href="/static/css/buttons.min.css" type="text/css" media="all">
<link rel="stylesheet" id="forms-css" href="/static/css/forms.min.css" type="text/css" media="all">
<link rel="stylesheet" id="l10n-css" href="/static/css/l10n.min.css" type="text/css" media="all">
<link rel="stylesheet" id="login-css" href="/static/css/login.min.css" type="text/css" media="all">
<link rel="stylesheet" type="text/css" href="/static/css/admin.css"> <meta name="robots" content="noindex,noarchive">
<meta name="referrer" content="strict-origin-when-cross-origin">
<meta name="viewport" content="width=device-width">
<style id="dark-reader-style" type="text/css">@media screen {

/* Leading rule */
html {
  -webkit-filter: invert(100%) hue-rotate(180deg) contrast(80%) !important;
  filter: invert(100%) hue-rotate(180deg) contrast(80%) !important;
}

/* Reverse rule */
img,
video,
:not(object):not(body)>embed,
object,
svg image,
[style*="background:url"],
[style*="background-image:url"],
[style*="background: url"],
[style*="background-image: url"],
[background],
twitterwidget {
  -webkit-filter: invert(100%) hue-rotate(180deg) !important;
  filter: invert(100%) hue-rotate(180deg) !important;
}
[style*="background:url"] *,
[style*="background-image:url"] *,
[style*="background: url"] *,
[style*="background-image: url"] *,
input,
[background] *,
img[src^="https://s0.wp.com/latex.php"],
twitterwidget .NaturalImage-image {
  -webkit-filter: none !important;
  filter: none !important;
}
.compatibility-with-darkreader-below-4-3-3 {
  background: white !important;
}

/* Text contrast */
html {
  text-shadow: 0 0 0 !important;
}

/* Full screen */
:-webkit-full-screen, :-webkit-full-screen * {
  -webkit-filter: none !important;
  filter: none !important;
}
:-moz-full-screen, :-moz-full-screen * {
  -webkit-filter: none !important;
  filter: none !important;
}
:fullscreen, :fullscreen * {
  -webkit-filter: none !important;
  filter: none !important;
}

/* Page background */
html {
  background: rgb(25,25,25) !important;
}

/* Custom rules */
.compatibility-with-darkreader-below-4-3-3 {
    background: white !important;
}

}</style></head>
<body class="login login-action-register wp-core-ui  locale-zh-cn">
<div id="login">
<h1><a>BocatCloud</a></h1>
<p class="message register">注册</p>
<form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
<p>
<label for="user_login">用户名<br>
<input type="text" name="username" id="user_login" class="input" value="" size="20" autocapitalize="off"></label>
</p>
<p>
<label for="user_email">密码<br>
<input type="text" name="password" id="user_email" class="input" value="" size="25"></label>
</p>
<br class="clear">
<input type="hidden" name="redirect_to" value="">
<p class="submit"><input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="注册"></p>
</form>
<p id="nav">
<a href="./userlogin">已有用户登录</a>
| <a href="./lostpassword">忘记密码？</a>
</p>
</div>
<script type="text/javascript">
	try{document.getElementById('user_login').focus();}catch(e){}
	if(typeof wpOnload=='function')wpOnload();
	</script>
<div class="clear"></div>


</body></html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/lostpassword.html
<!DOCTYPE html>
<!-- saved from url=(0046)https://vcb-s.com/wp-login.php?action=register -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN"><!--<![endif]--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>找回密码</title>
<link rel="dns-prefetch" href="https://s.w.org/">
<link rel="stylesheet" id="dashicons-css" href="/static/css/dashicons.min.css" type="text/css" media="all">
<link rel="stylesheet" id="buttons-css" href="/static/css/buttons.min.css" type="text/css" media="all">
<link rel="stylesheet" id="forms-css" href="/static/css/forms.min.css" type="text/css" media="all">
<link rel="stylesheet" id="l10n-css" href="/static/css/l10n.min.css" type="text/css" media="all">
<link rel="stylesheet" id="login-css" href="/static/css/login.min.css" type="text/css" media="all">
<link rel="stylesheet" type="text/css" href="/static/css/admin.css"> <meta name="robots" content="noindex,noarchive">
<meta name="referrer" content="strict-origin-when-cross-origin">
<meta name="viewport" content="width=device-width">
<style id="dark-reader-style" type="text/css">@media screen {

/* Leading rule */
html {
  -webkit-filter: invert(100%) hue-rotate(180deg) contrast(80%) !important;
  filter: invert(100%) hue-rotate(180deg) contrast(80%) !important;
}

/* Reverse rule */
img,
video,
:not(object):not(body)>embed,
object,
svg image,
[style*="background:url"],
[style*="background-image:url"],
[style*="background: url"],
[style*="background-image: url"],
[background],
twitterwidget {
  -webkit-filter: invert(100%) hue-rotate(180deg) !important;
  filter: invert(100%) hue-rotate(180deg) !important;
}
[style*="background:url"] *,
[style*="background-image:url"] *,
[style*="background: url"] *,
[style*="background-image: url"] *,
input,
[background] *,
img[src^="https://s0.wp.com/latex.php"],
twitterwidget .NaturalImage-image {
  -webkit-filter: none !important;
  filter: none !important;
}
.compatibility-with-darkreader-below-4-3-3 {
  background: white !important;
}

/* Text contrast */
html {
  text-shadow: 0 0 0 !important;
}

/* Full screen */
:-webkit-full-screen, :-webkit-full-screen * {
  -webkit-filter: none !important;
  filter: none !important;
}
:-moz-full-screen, :-moz-full-screen * {
  -webkit-filter: none !important;
  filter: none !important;
}
:fullscreen, :fullscreen * {
  -webkit-filter: none !important;
  filter: none !important;
}

/* Page background */
html {
  background: rgb(25,25,25) !important;
}

/* Custom rules */
.compatibility-with-darkreader-below-4-3-3 {
    background: white !important;
}

}</style></head>
<body class="login login-action-register wp-core-ui  locale-zh-cn">
<div id="login">
<h1><a>BocatCloud</a></h1>
<p class="message register">找回密码</p>
<form class="form-horizontal" method="post" action="{{ url_for('.reset_send') }}">    <p>
<label for="user_login">用户名<br>
<input type="text" name="username" id="user_login" class="input" value="" size="20" autocapitalize="off"></label>
</p>
<br class="clear">
<input type="hidden" name="redirect_to" value="">
<p class="submit"><input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="找回密码"></p>
</form>
<p id="nav">
<a href="/userlogin">登录</a>
| <a href="/lostpassword">忘记密码？</a>
</p>
</div>
<script type="text/javascript">
	try{document.getElementById('user_login').focus();}catch(e){}
	if(typeof wpOnload=='function')wpOnload();
	</script>
<div class="clear"></div>


</body></html>

templates/profile.html
{% extends "topic/base.html" %}
{% block title %}用户资料{% endblock%}
{% block main %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <link rel="stylesheet" href="/static/css/profile.css">#}
    <title>用户资料页面</title>
</head>
<body>

<div id="main">
    <!--在profile页面也增加sidebar 个人信息侧边栏-->
    <div id="sidebar">
        <div class="panel">

            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="">
                            <img src="{{ user.image }}" title="">
                                <span class="user_name"><a class="dark">{{ user.username }}</a></span>
                        </a>
                        <span class="user_name"><a class="dark"
                                                   href="{{ url_for('index.profile') }}"></a></span>

                        <div class="space clearfix"></div>
                        <span class="signature">
                            <p>{{ user.signature }}</p>
    </span>
                    </div>
                </div>


            </div>

        </div>

        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('topic.new', board_id=-1) }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('index.index') }}">主页</a><span class="divider">/</span></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src={{ user.image }} class="user_avatar" title="">
                </div>
                <a class="dark">{{ user.username }}</a>

                <p class="col_fade">注册于{{ user.created_time | format_time }}</p>

            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>

            {% for t in created %}
                <div class="cell">

                    <a class="user_avatar pull-left" href="{{ url_for('index.user_detail', id=t.user().id) }}">
                        <img src={{ user.image }}>
                    </a>
              <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                        {{ t.replies() | count }}
                    </span>
                    <span class="count_seperator">/</span>
                    <span class="count_of_visits" title="点击数">
                        {{ t.views }}
                     </span>
                 </span>


                    <a class="last_time pull-right"
                       href="{{ url_for('index.user_detail', id=t.user().id) }}">
                        <img class="user_small_avatar" src={{ user.image }}>
                        <span class="last_active_time">发布于{{ t.created_time | format_time }}</span>
                    </a>

                    <div class="topic_title_wrapper">

                        <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}"
                           title="">
                            {{ t.title }}
                        </a>
                    </div>
                </div>
            {% endfor %}

        </div>


    <div class="panel">
        <div class="header">
            <span class="col_fade">最近参与的话题</span>
        </div>
        {% for t in replied %}
            <div class="cell">

                <a class="user_avatar pull-left" href="">
                    <img src={{ t.user().image }}>
                </a>

                <span class="reply_count pull-left">
                <span class="count_of_replies" title="回复数">
                    {{ t.replies() | count }}
                </span>
            <span class="count_seperator">/</span>
                <span class="count_of_visits" title="点击数">
                    {{ t.views }}
                </span>
            </span>


                <a class="last_time pull-right"
                   href="{{ url_for('index.user_detail', id=t.user().id) }}">
                    <img class="user_small_avatar" src={{ t.user().image }}>
                    <span class="last_active_time">发布于{{ t.created_time | format_time }}</span>
                </a>


                <div class="topic_title_wrapper">


                    <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}"
                       title="">
                        {{ t.title }}
                    </a>
                </div>
            </div>
        {% endfor %}

    </div>
</div>
</div>
<<<<<<< HEAD
{% endblock %}
=======
{% endblock %}
>>>>>>> error fixed and gif added

templates/reset_view.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>密码重置</title>#}
{#    <link rel="stylesheet" href="/static/css/bootstrap.min.css">#}
{#</head>#}
{#<body>#}
{#    <form class="form-horizontal" method="post" action="{{ url_for('.reset_update',token=token, password=password) }}">#}
{#        <div class="control-group">#}
{#            <label class="control-label">新密码</label>#}
{#            <div class="controls">#}
{#                <input type="text" name="password" placeholder="password">#}
{#            <button type="submit">提交新密码</button>#}
{#            </div>#}
{#        </div>#}
{#    </form>#}
{#</body>#}
{#</html>#}

<!DOCTYPE html>
<!-- saved from url=(0046)https://vcb-s.com/wp-login.php?action=register -->
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN"><!--<![endif]--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>找回密码</title>
<link rel="dns-prefetch" href="https://s.w.org/">
<link rel="stylesheet" id="dashicons-css" href="/static/css/dashicons.min.css" type="text/css" media="all">
<link rel="stylesheet" id="buttons-css" href="/static/css/buttons.min.css" type="text/css" media="all">
<link rel="stylesheet" id="forms-css" href="/static/css/forms.min.css" type="text/css" media="all">
<link rel="stylesheet" id="l10n-css" href="/static/css/l10n.min.css" type="text/css" media="all">
<link rel="stylesheet" id="login-css" href="/static/css/login.min.css" type="text/css" media="all">
<link rel="stylesheet" type="text/css" href="/static/css/admin.css"> <meta name="robots" content="noindex,noarchive">
<meta name="referrer" content="strict-origin-when-cross-origin">
<meta name="viewport" content="width=device-width">
<style id="dark-reader-style" type="text/css">@media screen {

/* Leading rule */
html {
  -webkit-filter: invert(100%) hue-rotate(180deg) contrast(80%) !important;
  filter: invert(100%) hue-rotate(180deg) contrast(80%) !important;
}

/* Reverse rule */
img,
video,
:not(object):not(body)>embed,
object,
svg image,
[style*="background:url"],
[style*="background-image:url"],
[style*="background: url"],
[style*="background-image: url"],
[background],
twitterwidget {
  -webkit-filter: invert(100%) hue-rotate(180deg) !important;
  filter: invert(100%) hue-rotate(180deg) !important;
}
[style*="background:url"] *,
[style*="background-image:url"] *,
[style*="background: url"] *,
[style*="background-image: url"] *,
input,
[background] *,
img[src^="https://s0.wp.com/latex.php"],
twitterwidget .NaturalImage-image {
  -webkit-filter: none !important;
  filter: none !important;
}
.compatibility-with-darkreader-below-4-3-3 {
  background: white !important;
}

/* Text contrast */
html {
  text-shadow: 0 0 0 !important;
}

/* Full screen */
:-webkit-full-screen, :-webkit-full-screen * {
  -webkit-filter: none !important;
  filter: none !important;
}
:-moz-full-screen, :-moz-full-screen * {
  -webkit-filter: none !important;
  filter: none !important;
}
:fullscreen, :fullscreen * {
  -webkit-filter: none !important;
  filter: none !important;
}

/* Page background */
html {
  background: rgb(25,25,25) !important;
}

/* Custom rules */
.compatibility-with-darkreader-below-4-3-3 {
    background: white !important;
}

}</style></head>
<body class="login login-action-register wp-core-ui  locale-zh-cn">
<div id="login">
<h1><a>BocatCloud</a></h1>
<p class="message register">找回密码</p>
<form class="form-horizontal" method="post" action="{{ url_for('.reset_update',token=token, password=password) }}">   <p>
<label for="user_login">新密码<br>
<input type="text" name="password" id="user_login" class="input" value="" size="20" autocapitalize="off"></label>
</p>
<br class="clear">
<input type="hidden" name="redirect_to" value="">
<p class="submit"><input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="重置密码"></p>
</form>
<p id="nav">
<a href="/userlogin">登录</a>
| <a href="/lostpassword">忘记密码？</a>
</p>
</div>
<script type="text/javascript">
	try{document.getElementById('user_login').focus();}catch(e){}
	if(typeof wpOnload=='function')wpOnload();
	</script>
<div class="clear"></div>


</body></html>